# Copyright (c) 2018, 2019 Diamond Key Security, NFP  All rights reserved.
#
DKS_ROOT ?= $(abspath ../../../..)


LIBDKS_SRC ?= ${DKS_ROOT}/sw/libdks
LIBDKS_BUILD ?= $(abspath .)

include ${LIBDKS_SRC}/Makefile